### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by giannoulakis** [oCesaum/chat-gui#1]
https://github.com/oCesaum/chat-gui/blob/ef2f5f04c22a6f45ab12ee99bc7d6f92f3fada1c/src/Chat.jsx#L29
- Nao é legal usar props direto no jsx, coloca ele numa outra variavel antes, de preferencia la no inicio do componente

https://github.com/oCesaum/chat-gui/blob/ef2f5f04c22a6f45ab12ee99bc7d6f92f3fada1c/src/App.jsx#L9-L16
1 - nao precisa estar em useState, ja que nunca muda
2 - pq esta definido aqui  no App, e nao diretamente dentro do Chat, ja que so é usado dentro do Chat?

https://github.com/oCesaum/chat-gui/blob/ef2f5f04c22a6f45ab12ee99bc7d6f92f3fada1c/src/Chat.jsx#L29-L30
- VC esta renderizando na pagina TODOS os chats ao mesmo tempo, mas somente exibindo 1 via css. Consegue fazer renderizar somente o que esta ativo?

https://github.com/oCesaum/chat-gui/blob/main/src/Chat.jsx#L11
- variavel channel nao esta sendo usada, pode ser removida?

**Comment by oCesaum** [comment]
resolvido, a variável channel não pode ser removida

**Comment by oCesaum** [comment]
me equivoquei, a prop channel foi removida
